### PR TITLE
[RELEASE] v4.0

### PR DESCRIPTION
**Pull request by brandonscott**

### CODE REVIEW

**Comment by brandonscott** [comment]
This release has a lot of cool updates.

Notably:

* C# 6.0 Updates
* Integration Testing Tool
* Product Updates (Blade Stealth etc)
* New Tests

**Comment by njbmartin** [comment]
I remember there being an issue with one of the devices having an incorrect GUID. Are we certain the Blade's GUID is correct?

**Comment by brandonscott** [comment]
@njbmartin Unless you know something I don't, these are the GUIDs from the SDK 'Defines' file.  Which GUID had an incorrect GUID previously?  There was an issue where the Deathstalker and Diamondback could not be queried, but that has since been resolved.

**Comment by njbmartin** [comment]
Yeah, that's the issue I was referring to. Wasn't that an issue on the SDK side?

**Comment by brandonscott** [comment]
Yes, it was.  It's sorted now.

**Pull request merged**
