### PR TITLE
[WIP] Added drawing namespace for simplifying complex CustomGrids.

### PR DESCRIPTION
**Pull request by xChris6041x**
This pull request simplifies rendering complex CustomGrids to the keyboard.

The namespace includes the ChromaGraphics object which acts like the System.Drawing.Graphics but for keyboard rendering. This also takes in account transparency within the ChromaGraphics object using the ColorF structure for colors. Building CustomGrids with this namespace is much more simple than modifying the CustomGrid itself.

There are a few more things I would like to add such as Gradients, but I would like some feedback and a possible addition to the Colore Library :smile:.

### CODE REVIEW

**Comment by Sharparam** [comment]
Rebase against develop branch, it was out of sync with the master branch (my bad!), that's why those 3 commits by me are in there.

Did you branch off of `master` in your drawing branch? You should branch from develop in the future, to make sure you are developing on the latest changes, and not the last release (which would normally be quite a bit behind).

It might be sufficient to just rebase and push and let the PR update, but you may have to open a new PR if it gets too messy.

**Comment by xChris6041x** [comment]
I did get it from the master branch, sorry about that. I'm new to contributing to other projects through git so not sure how to rebase to develop.

**Comment by Sharparam** [comment]
It's not you, we had completely forgotten about adding that to the contributing guidelines, so there's no way you could know :P

**Comment by Sharparam** [comment]
You should be able to do `git checkout develop` on your fork, then cherry pick your added commits, so it'd be something like this:

```
git checkout develop
git cherry-pick fea9960 d0558f6
```

**Comment by Sharparam** [comment]
@xChris6041x: What's the status?

**Comment by xChris6041x** [comment]
@Sharparam I will have it done soon. Because it was getting messy I decided to remove the branch and create a new one off develop. Just have to fix some naming :smile:.

**Pull request closed without merging**
