### PR TITLE
[RELEASE] v5.2

### PR DESCRIPTION
**Pull request by Sharparam**
Final release in the 5.x line.

This release should be stable and support most things, but it cannot be guaranteed. Most effort to get the Colore project to an acceptable standard again will be put into the 6.0 release.

@njbmartin It is important you review this ASAP.

@WolfspiritM @roxaskeyheart If you guys are still active and interested in the Colore project I would be very interested in hearing your thoughts on the release and the future of the project.

### CODE REVIEW

**Comment by WolfspiritM** [comment]
@Sharparam Thanks for getting this ready! 👍 

I'm still active and using Colore. I moved GameDog to the REST API but moved back to Colore as I don't trust that one for now (especially when it comes to speed I need to test more intense how capable the REST API is before completly moving over) and was hoping for a release soon to use it for GameDog (currently I've build the dev branch for test and preview builds to get ChromaLink working). Sooner or later I will move over to the REST API for at least most of my apps but I think it completely depends on the usecase. I think when it comes to speed, which is essential for Gameintegrations, Colore and C++ is still much faster then the REST API as it avoids all the HTTP and TCP overhead. While for tools and small apps the REST API might be better. So I think Colore is still very usefully as long as the C++ API is around (so probably forever) and when I get the time I will also help to keep Colore up to date for any upcoming changes.

**Comment by Sharparam** [comment]
The move to .NET Standard and release 6.0 should hopefully make it easier to contribute to Colore, as I will cut a lot of cruft out like the many conditionals for platform builds.

I would also like to abstract away the SDK implementation to make it possible to plug in different "backends" for Colore (Native SDK and REST API being supplied as NuGet packages).

I haven't decided how exactly those should be implemented. I'm leaning towards a DI/IoC solution with some factories provided for users that are not using IoC in their project.

```csharp
var chroma = SdkFactory.Create();
chroma.Keyboard.SetAll(Color.Red);

// or
var chroma = RestFactory.Create();
chroma.Keyboard.SetAll(Color.Red);

// or with some kind of DI support
services.AddColore(ioc => ioc.AddSingleton<IApiImplementation, SdkApiImplementation>());
var chroma = services.GetService<IChroma>();
chroma.Keyboard.SetAll(Color.Red);
```

**Comment by Sharparam** [comment]
@WolfspiritM I'm playing around with .NET Standard support now, and some multi-targeting.

It's currently building for .NET Standard 1.3 and .NET Framework 4.5.1. This is quite a bump compared to our previously lowest supported framework 3.5. You can see the artifacts here: https://ci.appveyor.com/project/Corale/colore/build/artifacts

.NET Framework 3.5 is growing quite old so it would be nice to drop support for it, but I'm unsure if there are a lot of people using it and so would be depending on Colore supporting that version. What is the status in your case?

**Comment by WolfspiritM** [comment]
@Sharparam .NET Standard 1.3 sounds great.
I even moved to .NET 4.7 for GameDog and all my tools are 4.5.1 minimum.
I also think 3.5 is outdated and shouldn't be used anymore.
Even Windows 10 includes 4.6 by default.
Only thing I can think of that could cause trouble if 3.5 is not supported anymore is Unity but there is a REST API alternative for that.

I'm not sure if the "pluggable" backend is really needed. I think Colore should focus on the C++ side. I've already built a wrapper around the .NET Core/Standard REST API implementation which allows me to easily switch between that and Colore depending on what DLLs are loaded. I can make that public if you like.

**Comment by Sharparam** [comment]
@WolfspiritM Your DLL switching logic would be interesting to see!

The pluggable backend comes sortof as a bonus to something I've been wanting to do for a while: Decouple the Colore part from the SDK implementation. We've been unable to write a lot of unit tests because of this strong coupling with a bunch of static classes that call directly to the C++ SDK.

**Comment by njbmartin** [comment]
There was a lot to go through, so I took a look at each commit individually. Everything looks solid, with the only concern being CI reporting.

**Comment by Sharparam** [comment]
Thank you for the review @njbmartin! CI reporting will be running on all future stuff made after this release (it's currently active on the develop branch and any other branch from there).

**Pull request merged**
