### PR TITLE
Update Clear to use Effect.None for all devices

### PR DESCRIPTION
**Pull request by njbmartin**
- [X] Update Clear to use Effect.None for all devices
- [X] 	Make Device.Clear abstract

### CODE REVIEW

**Comment by Sharparam** [comment]
Looks good, maybe change the documentation on the individual devices to say "Clears the current effect on this `{device_type_here}`.".

**Comment by njbmartin** [comment]
Will get that updated.

**Comment by brandonscott** [comment]
Looks good, I'm happy with this.  @Sharparam to merge?

**Comment by Sharparam** [comment]
Yep, looks good.

**Comment by brandonscott** [comment]
@njbmartin Please delete branch when ready.

**Pull request merged**
