### PR TITLE
[WIP] Added drawing namespace for simplifying complex CustomGrids.

### PR DESCRIPTION
**Pull request by xChris6041x**
This pull request simplifies rendering complex CustomGrids to the keyboard.

The namespace includes the ChromaGraphics object which acts like the System.Drawing.Graphics but for keyboard rendering. This also takes in account transparency within the ChromaGraphics object using the ColorF structure for colors. Building CustomGrids with this namespace is much more simple than modifying the CustomGrid itself.

There are a few more things I would like to add such as Gradients, but I would like some feedback and a possible addition to the Colore Library :smile:.

### CODE REVIEW

**Comment by Sharparam** [comment]
**ColorF.cs:**
The alpha component of `ColorF` doesn't seem to be used outside of the struct itself, this makes it tempting to implement the ColorF functionality in the existing color struct.

The C++ (WinAPI) `COLORREF` that Core.Color is translated to, defines itself as `0x00BBGGRR`, I'm unsure if it cares about those leftmost digits. Can you do some testing to see if it does? If not, we can use those to store alpha values, and not need two different color structs, which can end up confusing.

**ChromaGraphics.cs / Core.cs**
These look like they can be merged into the existing `Keyboard` class, with the benefit that they'll be in the same place as the other keyboard functions. You can use the `_grid` field in Keyboard as a replacement for the `_grid` field in your graphics classes (use `_grid[row, column]` property on the `CustomGrid` struct to get/set colors).

The `Clear` method should be able to just call the existing `Clear` method on the `Keyboard` class, as its only function is to clear every key(?). I don't have a keyboard to test currently, but it should clear the logo as well.

**StyleCop**
(Note that when moving code and merging to other classes as I suggested above, the warnings below will not correspond to the code anymore, you should [install StyleCop](https://stylecop.codeplex.com/) yourself and run it to see what needs addressing.)

The following StyleCop violations and compile warnings need addressing:
```
Missing XML comment for publicly visible type or member 'Corale.Colore.Drawing.ChromaGraphics.LogoX' (Core.cs, Line 45, Column 26)
Missing XML comment for publicly visible type or member 'Corale.Colore.Drawing.ChromaGraphics.LogoY' (Core.cs, Line 46, Column 26)
Missing XML comment for publicly visible type or member 'Corale.Colore.Drawing.ChromaGraphics.ChromaGraphics()' (Core.cs, Line 50, Column 16)
SA1600: CSharp.Documentation: The field must have a documentation header. (Core.cs, Line 45, Column 1)
SA1600: CSharp.Documentation: The field must have a documentation header. (Core.cs, Line 46, Column 1)
SA1600: CSharp.Documentation: The field must have a documentation header. (Core.cs, Line 48, Column 1)
SA1600: CSharp.Documentation: The constructor must have a documentation header. (Core.cs, Line 50, Column 1)
SA1505: CSharp.Layout: An opening curly bracket must not be followed by a blank line. (Core.cs, Line 43, Column 1)
SA1507: CSharp.Layout: The code must not contain multiple blank lines in a row. (Core.cs, Line 64, Column 1)
SA1507: CSharp.Layout: The code must not contain multiple blank lines in a row. (Core.cs, Line 81, Column 1)
SA1507: CSharp.Layout: The code must not contain multiple blank lines in a row. (Core.cs, Line 82, Column 1)
SA1505: CSharp.Layout: An opening curly bracket must not be followed by a blank line. (Core.cs, Line 113, Column 1)
SA1507: CSharp.Layout: The code must not contain multiple blank lines in a row. (Core.cs, Line 128, Column 1)
SA1507: CSharp.Layout: The code must not contain multiple blank lines in a row. (Core.cs, Line 129, Column 1)
SA1201: CSharp.Ordering: All methods must be placed after all properties. (Core.cs, Line 133, Column 1)
SA1108: CSharp.Readability: A comment may not be placed within the bracketed statement. (Core.cs, Line 112, Column 1)
SA1600: CSharp.Documentation: The field must have a documentation header. (ColorF.cs, Line 41, Column 1)
SA1600: CSharp.Documentation: The field must have a documentation header. (ColorF.cs, Line 42, Column 1)
SA1600: CSharp.Documentation: The field must have a documentation header. (ColorF.cs, Line 43, Column 1)
SA1600: CSharp.Documentation: The field must have a documentation header. (ColorF.cs, Line 44, Column 1)
SA1614: CSharp.Documentation: The documentation text within the param tag for the '<param name="color" />' parameter must not be empty. (ColorF.cs, Line 78, Column 1)
SA1614: CSharp.Documentation: The documentation text within the param tag for the '<param name="color" />' parameter must not be empty. (ColorF.cs, Line 88, Column 1)
SA1614: CSharp.Documentation: The documentation text within the param tag for the '<param name="color" />' parameter must not be empty. (ColorF.cs, Line 97, Column 1)
SA1614: CSharp.Documentation: The documentation text within the param tag for the '<param name="color" />' parameter must not be empty. (ColorF.cs, Line 107, Column 1)
SA1614: CSharp.Documentation: The documentation text within the param tag for the '<param name="color" />' parameter must not be empty. (ColorF.cs, Line 116, Column 1)
SA1615: CSharp.Documentation: The documentation header must contain a returns tag since the element has a return value. (ColorF.cs, Line 207, Column 1)
SA1616: CSharp.Documentation: The returns section in the documentation header must not be empty. (ColorF.cs, Line 224, Column 1)
SA1616: CSharp.Documentation: The returns section in the documentation header must not be empty. (ColorF.cs, Line 240, Column 1)
SA1504: CSharp.Layout: An accessor can only be placed on a single line if all of the accessors in the property are placed on a single line. (ColorF.cs, Line 126, Column 1)
SA1504: CSharp.Layout: An accessor can only be placed on a single line if all of the accessors in the property are placed on a single line. (ColorF.cs, Line 146, Column 1)
SA1504: CSharp.Layout: An accessor can only be placed on a single line if all of the accessors in the property are placed on a single line. (ColorF.cs, Line 166, Column 1)
SA1504: CSharp.Layout: An accessor can only be placed on a single line if all of the accessors in the property are placed on a single line. (ColorF.cs, Line 186, Column 1)
SA1505: CSharp.Layout: An opening curly bracket must not be followed by a blank line. (ColorF.cs, Line 32, Column 1)
SA1505: CSharp.Layout: An opening curly bracket must not be followed by a blank line. (ColorF.cs, Line 39, Column 1)
SA1507: CSharp.Layout: The code must not contain multiple blank lines in a row. (ColorF.cs, Line 201, Column 1)
SA1507: CSharp.Layout: The code must not contain multiple blank lines in a row. (ColorF.cs, Line 245, Column 1)
SA1614: CSharp.Documentation: The documentation text within the param tag for the '<param name="includeLogo" />' parameter must not be empty. (ChromaGraphics.cs, Line 69, Column 1)
SA1505: CSharp.Layout: An opening curly bracket must not be followed by a blank line. (ChromaGraphics.cs, Line 40, Column 1)
SA1507: CSharp.Layout: The code must not contain multiple blank lines in a row. (ChromaGraphics.cs, Line 82, Column 1)
SA1507: CSharp.Layout: The code must not contain multiple blank lines in a row. (ChromaGraphics.cs, Line 83, Column 1)
SA1507: CSharp.Layout: The code must not contain multiple blank lines in a row. (ChromaGraphics.cs, Line 234, Column 1)
SA1507: CSharp.Layout: The code must not contain multiple blank lines in a row. (ChromaGraphics.cs, Line 235, Column 1)
SA1507: CSharp.Layout: The code must not contain multiple blank lines in a row. (ChromaGraphics.cs, Line 276, Column 1)
SA1507: CSharp.Layout: The code must not contain multiple blank lines in a row. (ChromaGraphics.cs, Line 314, Column 1)
SA1508: CSharp.Layout: A closing curly bracket must not be preceded by a blank line. (ChromaGraphics.cs, Line 315, Column 1)
```

[These StyleCop warnings are grammatical/doctext related, fix them if you want, but it's not super important (for an idea of how doctext for properties and constructors are written, have a look at the existing code in Colore).](https://gist.github.com/Sharparam/7e98525b0d678afb8b6e)

**Comment by xChris6041x** [comment]
@Sharparam 

I will make sure I get StyleCop on my PC and fix those mistakes. 

I can look into how to use the current Color object (not very fluent with byte shifting and such). But once I get that I can do some testing.

In regards to combining the Graphics methods into the Keyboard class, I think that it would give the Keyboard too many responsibilities and make it too complex. The responsibility of the ChromaGraphics class is to build CustomGrids, which i don't believe is the job of the Keyboard. Let me know what you think about this.

I also noticed I was being a little hypocritical about the single responsibility. The ColorF methods like blend and inverse should be in a ColorMath utility class.

I also made sure there were enough Clear overloads to include not clearing the logo and clearing it to a color as well.

**Comment by Sharparam** [comment]
Calling `Keyboard.Instance.FillRectangle` and `Set(Image, ...)` feels intuitive for me. You have a point about making Keyboard too complex though. There is a point where a class just has too much code in it, I'm not sure where we want to set that limit with Colore.

The `Blend` and `Inverse` methods could be kept in `ColorF`, possibly make them static pure methods, which I think is the recommended .NET way. (Pure method = No side effects). So they'd take in two colors, the first one being instead of operating on the current instance with `this`.

You can utilise parameter default values to reduce the code needed for all your Clear overloads too, `void Clear(ColorF color, bool clearLogo = false)`.

Thinking about it, clear methods that don't clear the logo could probably be useful on the main `Keyboard` class too, in case someone wants to keep the Razer Green on the logo while coloring the rest of the keyboard. That's a subject for another pull request or issue, though.

**Comment by xChris6041x** [comment]
It is easier, but I don't think it is good design. When I use the System.Drawing, there is a Image class and a separate class for manipulating the Image. This makes maintaining the code much easier, because if Razer decides to release a new product that acts like the Blackwidow Chroma with it's coloring, then it's simple to implement in a single class. Then if you wanted to you could render the something to both devices (maybe even support for two keyboards).

I agree that the Inverse and Blend methods should be static and pure. We can try that left in the ColorF class, but if they get way too complicated they could be in another class. Like with System.Drawing, there are not many (if any) math methods in it. The clear methods could be added to the Keyboard, but I don't think they need to be as complex. Maybe just a Clear(bool includeLogo = false) that clears it to black.

**Comment by Sharparam** [comment]
Can you elaborate on the topic about new devices and implementations? With the tools that exist, I don't see how splitting a class up in partials (given the small size of them here) helps much. The general consensus in the .NET community seems to be to only split when a class contains inner classes/interfaces/structs or for generated code (the most common example being the `Designer.cs` files in WinForms projects).

Also, are float overloads for the various drawing functions needed? I don't see how they belong. Especially for Image methods, images can't have fractions of a pixel. Rectangles commonly aren't defined with fractions in their dimensions either. Removing them would increase maintainability and lower the size of the class, adding more incentive to remove the partial structure.

**Comment by xChris6041x** [comment]
I was referring to keeping the Keyboard and Graphics object separate. This is better design because then two keyboards (if that would ever be possible) could use the same Graphics object instead of drawing the same thing twice.

The reason I had them sperate was for readability and the using statements are different. Since I used the Colore color system more often in the core, and System.Drawing the the ChromaGraphics.

I also just put the float overloads for convenience. A lot of graphics engines use floats then round them in the background, But if you don't want them I can remove them.

**Comment by Sharparam** [comment]
Not sure what you're going at with the two keyboards things. Currently, the Chroma SDK itself has nothing that suggests differentiating two devices, so if it was ever implemented, an overhaul of both Chroma SDK (and thus Colore) would be needed anyway. The core Keyboard class (`Corale.Colore.Core.Keyboard`) as is would/does not support multiple devices either.

If the SDK even supports it internally, it probably just mirrors the API calls to all connected devices right now.

If anything, having ChromaGraphics/Core not be a singleton suggests creating multiple instances rather than one shared.

Either way, Colore should reflect the current features/functionality of the Chroma SDK, and not potential future additions that may or may not be implemented. As said above, if such needs arise, it will change Chroma SDK enough that Colore would need a major update anyway.

As for the floats, I think remove them for now. If people start asking for them we can add them back.

Combining the two partials into one class ends up at about 168 lines (not counting comments and file header and with float overloads removed), meaning the class is nowhere near complex enough to be separated. As for different namespaces for different colors, use FQN for the System.Drawing color and just `Color` for the Colore struct.

**Comment by Sharparam** [comment]
What's the status on this PR?

**Comment by Sharparam** [comment]
Closing due to inactivity, if there's any progress then feel free to re-open!

**Pull request closed without merging**
