### PR TITLE
Fix keyboard custom

### PR DESCRIPTION
**Pull request by njbmartin**
Now uses the correct Keyboard Effect for a number of methods.

### CODE REVIEW

**Comment by Sharparam** [comment]
The `Custom` designator for the effect is misleading as the actual effect getting set (`Razer.Keyboard.Effects.Custom`) implements `CUSTOM_KEY`. The API (and headers) gave the implication that `CUSTOM_KEY`'s regular mode (using only the color array and not keys array) was supposed to be identical to the old `CUSTOM` when not having set any key colors.

We should check with Razer first to make sure the non-key array on `CUSTOM_KEY` not setting positional keys is a bug, I think.

**Comment by njbmartin** [comment]
There should be a separation between CUSTOM and CUSTOM_KEY. CUSTOM_KEY is purely for usage with RZKEYS, where as CUSTOM is a pure grid.

**Comment by Sharparam** [comment]
`CUSTOM_KEY` has the normal grid layer as well though. With the "keys" part as an optional additional array that can be passed. So the idea should be that it can be used for both, but this is seemingly not the case then.

I say we still get some clarification from Razer before reverting to having two different (but near identical) grid implementations. If nothing in the "keys" array is set, then logically it should (and is documented to) fall back to the regular grid definition within `CUSTOM_KEY`.

**Comment by njbmartin** [comment]
I've already raised the issue of consistency between devices, in the case of the Deathstalker, I'd imagine CUSTOM_KEY isn't implemented.

**Comment by njbmartin** [comment]
Also, using a grid reference for CUSTOM_KEY makes no sense. _KEY refers to the use of RZKEY and not a grid reference.

**Comment by Sharparam** [comment]
The `CUSTOM_KEY` effect has two arrays in the SDK implementation. One that acts exactly as the grid in `CUSTOM`, and the second which is for setting `RZKEY` values, which are only active when flagged with `0x01000000`, otherwise falling back to the regular grid.

So our implementation simply follows that.

**Comment by Sharparam** [comment]
To maintain compatibility with the Deathstalker we'd then have to add the old `Custom` back, but there should be a cleaner way of doing it.

Simply changing the effect type when passing the `Custom` (key) effect is non-ideal as we're not actually passing a `CUSTOM` effect struct and it may break in the future.

**Comment by njbmartin** [comment]
It's in their backlog to investigate 👍

**Comment by Sharparam** [comment]
Have there been any news on this?

**Comment by roxaskeyheart** [comment]
I was playing with this PR the other day and when I implement the changes, I can get my Deathstalker to work but my BlackWidow Chroma breaks then. Not sure if I was just doing something wrong though.

**Comment by Sharparam** [comment]
Yeah, that's the crux of it. Word was that Razer was going to investigate the change but I'm not sure on the status of that investigation.

**Comment by Sharparam** [comment]
Closing this in favor of #243.

**Pull request closed without merging**
