### PR TITLE
[WIP] Added drawing namespace for simplifying complex CustomGrids.

### PR DESCRIPTION
**Pull request by xChris6041x**
This pull request simplifies rendering complex CustomGrids to the keyboard.

The namespace includes the ChromaGraphics object which acts like the System.Drawing.Graphics but for keyboard rendering. This also takes in account transparency within the ChromaGraphics object using the ColorF structure for colors. Building CustomGrids with this namespace is much more simple than modifying the CustomGrid itself.

There are a few more things I would like to add such as Gradients, but I would like some feedback and a possible addition to the Colore Library :smile:.

@Sharparam Hopefully this is the last time I have to send this pull request.

### CODE REVIEW

**Comment by Sharparam** [comment]
You have targeted the master branch again :P
Recreate with develop as the target.

**Comment by xChris6041x** [comment]
@Sharparam Would using the rebase develop drawing then re publishing fix that?

**Comment by Sharparam** [comment]
You can just make a new pull request with the drawing branch, and selecting
"develop" instead of master in the dropdown. From what I can see the
commits on your drawing branch are properly synced, it's just the wrong
target branch on the pull request.

**Comment by Sharparam** [comment]
Closing this since a new one was made.

**Pull request closed without merging**
