### PR TITLE
Update devices to use Custom effects where available

### PR DESCRIPTION
**Pull request by Sharparam**
This PR updates all devices to make use of `Custom` effects rather than `Static` for updating basic colors.

Also updates the non-Keyboard `Custom` structs to have more functionality similar to Keyboard's.

### CODE REVIEW

**Comment by brandonscott** [comment]
The code looks good.  To confirm this is more of a convenience enhancement for developers so they can set colors more intuitively.

**Comment by njbmartin** [comment]
Yep, the expectancy of SetAll is of an immediate effect. Have been asked this by a number of developers using Colore.

**Comment by brandonscott** [comment]
Signing off on this once exception message is consistent. Feel free to merge after that.

**Comment by Sharparam** [comment]
Merging with @brandonscott's blessing.

**Pull request merged**
